{% set version = "2.0.0" %}

package:
  name: smpeg2
  version: {{ version }}

source:
  url: https://www.libsdl.org/projects/smpeg/release/smpeg2-{{ version }}.tar.gz
  sha256: 979a65b211744a44fa641a9b6e4d64e64a12ff703ae776bafe3c4c4cd85494b3
  patches:
    - windows_find_memset.patch  # [win]

build:
  number: 2

requirements:
  build:
    - cmake  # [win]
    - autoconf  # [unix]
    - automake  # [unix]
    - libtool  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pkgconfig  # [unix]
    - sdl2

test:
  requires:
    - python {{ environ['PY_VER'] + '*' }}  # [win]
  commands:
    - test -f $PREFIX/lib/libsmpeg2.a  # [unix]
    - test -f $PREFIX/lib/libsmpeg2.dylib  # [osx]
    - test -f $PREFIX/lib/libsmpeg2.so  # [linux]
    - test -f $PREFIX/bin/plaympeg  # [unix]
    - test -f $PREFIX/bin/smpeg2-config  # [unix]
    - test -f $PREFIX/include/smpeg2/smpeg.h  # [unix]
    - test -f $PREFIX/include/smpeg2/MPEG.h  # [unix]
    - if not exist %LIBRARY_LIB%\\smpeg2.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\smpeg2.dll exit 1  # [win]
    - if not exist %LIBRARY_INC%\\smpeg2\\smpeg.h exit 1  # [win]
    - if not exist %LIBRARY_INC%\\smpeg2\\MPEG.h exit 1  # [win]

about:
  home: https://www.libsdl.org/
  license: GPLv2
  license_file: COPYING
  summary: "SDL2 Mpeg2 libraries"
  description: MPEG2 Libraries for SDL2.

extra:
  recipe-maintainers:
    - dschreij
