travis:
  secure:
    BINSTAR_TOKEN: B+2sKygmo/bG1bsAHt5Z2amHhDvlT4rASvAIWGrQsxlklxHj0pABLRDBHs+6vpoNivDjel4RR+6cq0zWMm8FkyC4AHwu+R67o6sRccX6pEJVgMsgprYCRbL5Vui3Sq9dPWGLdacS7iOmE4iQmK32/gtByLft16apYoBQCouLFCmXQ8ga3OUdFw5B9GIjL/Vjajh0tMVgsqkRbbDJbUEKxn1+bV3MkAXz3eLP0evnfR87MgduqcPq9D+dAIV3Gu9mXuFLMO8YcaX8YqqclEyiZFDQqqCAlpoZa/qrDF5SxEcXXjShPI63QVVmF4X9bieDKyI27FcaaRMUdkWk7IP0YZO33tPr4CU89640rMgVO8Jh0dbPERziZPXa0mgu8XGsxGOkD6dafCG0cdcUYeY2SY2v+M/NFIL1WLimjtkld0rFP+EUjuoHsOdfy3FoMMUDODmHR4hhh6p2iVXVijy/hL2+dYT+UxCNvC4zt3EjHm3Axqg8Sgkbe4ECIKljFH14nTVyS3BCEAOyKZZSaemD6ZmNqTG+OZaj99fcZhIJiv0BUENVuQ9xhG8tKpk56m6BsJRl6DisiruSIRY4rSBBVnIM6L4XOtjoYabovfhlPgm1FyVrTNEl3DAl0wCDrcImAAdiC7zh6UehJGHLu5Wj5iMRGj/pe3j7qFR70LpPc0c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
