travis:
  secure:
    BINSTAR_TOKEN: mTpx8aH9cw7HkYjaoxECDsxocjB2JdP7wYJTKyAS7M3NxfBosKXMhv74XgK/4paZzt0VLDYTDp4fPes+LdJUxJGiZ1Flx90Hn/X4x3gaLk4UtmV0XllLkwDYOrvphrQgO+bkzncPJQ3IJIaa6ZJO+mhd+ivB9jn7YbUzPNNYyVWcl9O1rY4KlMBf/nRdYttR0d2bw82Uk3WwaspB1s2BRmzp+KSCNGeVWg0lktdNdbtBS9mXZY/BuXrgiLaBBfeo3vBFjLYFgla3EHv2Bbc69+WKo8VWD5Lc5BT3ayjqq56jl2QaljIJZwsEqf0E33R9DulGydpgB2bYAeYA5TGI2kQe1bn/TYWwSw0zbhLYJVjC4B94pRJr4b7bjz3YcG19cU95g/3DG3/nmbeTHlxNwsArN7jTLD0fBewwROD19UFTHFM5gzrTTwjCsWk7AYFHKAtsDJvjxL0c7AwTR+9YNtqvWO7xwBf/qrW0Ufz+LVgyRioAx12bMynno/JZAhKswwvAOyuiBZYM+AtwBCxQXiVRQpL2bDry/LdSCjMjf3z0mLjOO6Ir0lKXy8RbEIl+BAWWnkLkeyMMukusv/BHBSXK5nlKYP/Eqy7EhSH84WDxURZfZUCk5AssB7QYKtKycTRCKi+t3MlPN++JyNc1xmdmr7FSJLCCviMCRtnhw1w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
